# syntax=docker/dockerfile:1.7
FROM scratch
ARG UOS_ROOTFS_SHA256=unknown
LABEL org.opencontainers.image.title="Debian buster arm64 central build environment" \
      org.opencontainers.image.description="Debian buster arm64 bootstrap matching the UOS20E build ABI" \
      org.opencontainers.image.source="https://github.com/FishMagic/uos20-oci" \
      com.fishmagic.uos20e.apt-sources="debian.sources" \
      com.fishmagic.uos20e.rootfs-sha256="$UOS_ROOTFS_SHA256"
ADD rootfs.tar /
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8
WORKDIR /work
ENTRYPOINT ["/bin/bash"]
